variables:
  DEST_DIR: /topvisor/topvisor-com-static
  gitlabIp: 10.100.17.43
  gitlabPort: 30022
  projectUrl: ssh://git@$gitlabIp:$gitlabPort/$CI_PROJECT_PATH.git

stages:
  - pull
  - manual
  - trigger

install-depot-tools:
  script: |
    git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
    ./depot_tools/gclient
  cache: 
    paths:
      - depot_tools/

fetch-v8:
  script: |
    mkdir v8-src
    cd v8-src
    ./depot_tools/fetch v8
    cd v8
  cache:
    paths:
      - v8-src/

build-v8:
  script: |
    cd v8-src/v8
    ../../depot_tools/gclient sync
    ./build/install-bulid-deps.sh
    ./tools/dev/gm.py x64.release.check
   . 
     

