name: build-v8

on:
  schedule:
    # запуск ежегодно (в 00:00, 15-го января, независимо от дня недели)
    - cron: "0 0 15 1 *"
  push:
    # запуск только при пуше в мастер
    branches:
      - "master"
    # запуск, если изменился код пакета или пайплайна
    paths:
      - ".github/workflows/**/*"

jobs:
  build-v8:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v3

      - name: install gclient
        run: |
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          PATH=$GITHUB_WORKSPACE/depot_tools:$PATH
          gclient

      - name: download v8
        run: |
          mkdir v8-src && cd v8-src
          PATH=$GITHUB_WORKSPACE/depot_tools:$PATH
          fetch v8

      - name: sync v8
        run: |
          cd v8-src/v8
          PATH=$GITHUB_WORKSPACE/depot_tools:$PATH
          gclient sync

      - name: build v8
          pwd
          ls -la
          PATH=$GITHUB_WORKSPACE/depot_tools:$PATH
          ./v8-src/v8/build/install-bulid-deps.sh
          ./v8-src/v8/tools/dev/gm.py x64.release.check

      - name: get needed files for debian package
        run: |
          cd ./out/x64.release
          mkdir -p "$GITHUB_WORKSPACE/v8js/topvisor/v8js"
          cp ./d8 ./snapshot_blob.bin "$GITHUB_WORKSPACE/v8js/topvisor/v8js"

      #- name: change v8 version
      #  run: |
                             
      - name: build debian package
        run: |
          dpkg-deb --build v8js

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: v8js
          path: ./v8js.deb
